version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0

  apigateway.webapi:
    image: ${DOCKER_REGISTRY-}apigatewaywebapi
    build:
      context: .
      dockerfile: src/ApiGateway.WebApi/Dockerfile

volumes:
  portainer_data: null
  elasticsearch_data: null

networks:
  elasticsearch_net:
    driver: bridge